# -*- coding = utf-8 -*-
# @Time : 2022/2/3 16:38
# @Author : xzh
# @File : box_and_accessories.py
# @Software: PyCharm
from rich.console import Console

# å®ä¾‹åŒ–ä¸€ä¸ªè¾“å‡ºæ§åˆ¶ç«¯
console = Console()


def bolt(d_f_float):
    d_f_list_preferred = (3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 30, 36)
    d_f_list = (3, 4, 5, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 27, 30, 36)
    d_f = 0
    for i in d_f_list_preferred:
        if d_f_list_preferred[i] > d_f_float:
            if d_f_list_preferred[i] - d_f_float > d_f_float - d_f_list_preferred[i - 1]:
                d_f = d_f_list_preferred[i - 1]
                break
            else:
                d_f = d_f_list_preferred[i]
                break
    return d_f


def number_of_anchor_screws(a):
    if a <= 250:
        n = 4
    elif 500 > a > 250:
        n = 6
    else:
        n = 8
    return n


def structural_dimensions_of_bosses_and_flanges(d_1):
    table_11_2 = {'6': (12, 10),
                  '8': (13, 11),
                  '10': (16, 14),
                  '12': (18, 16),
                  '14': (20, 18),
                  '16': (22, 20),
                  '18': (24, 22),
                  '20': (26, 24),
                  '22': (30, 26),
                  '24': (34, 28),
                  '27': (36, 32),
                  '30': (40, 34)}
    return table_11_2[str(int(d_1))]


def hole_cover(a_sum):
    table_11_4 = [(140, 125, 120, 105, 7, 8, 4, 5),
                  (180, 165, 140, 125, 7, 8, 4, 5),
                  (220, 190, 160, 130, 11, 8, 4, 15),
                  (270, 240, 180, 150, 11, 8, 6, 15)]
    if a_sum <= 250:
        return table_11_4[0]
    elif 250 < a_sum <= 425:
        return table_11_4[1]
    elif 425 < a_sum <= 500:
        return table_11_4[2]
    elif 500 < a_sum <= 650:
        return table_11_4[3]
    else:
        pass


def vent_plug(d):
    table_11_5 = {'12': (18, 16.5, 14, 19, 10, 2, 4),
                  '16': (22, 19.6, 17, 23, 12, 2, 5),
                  '20': (30, 25.4, 22, 28, 15, 4, 6),
                  '22': (32, 25.4, 22, 29, 15, 4, 7),
                  '27': (38, 31.2, 27, 34, 18, 4, 8),
                  '30': (42, 36.9, 32, 36, 18, 4, 8),
                  '33': (45, 36.9, 32, 38, 20, 4, 8),
                  '36': (50, 41.6, 36, 46, 25, 5, 8)}
    return table_11_5[str(int(d))]


class box:
    def __init__(self, a):
        console.print("å‚è€ƒå‚è€ƒæ–‡çŒ®[1]è¡¨11ï¼ï¼‘ï¼ˆé“¸é“å‡é€Ÿå™¨ç®±ä½“ç»“æ„å°ºå¯¸ï¼‰ï¼Œåˆæ­¥å–å¦‚ä¸‹å°ºå¯¸ï¼š", style='#FF6100')
        if 0.025 * a + 3 < 8:
            self.delta = 8
        else:
            self.delta = 0.025 * a + 3
        if 0.02 * a + 3 < 8:
            self.delta_1 = 8
        else:
            self.delta_1 = 0.02 * a + 3
        self.b = 1.5 * self.delta
        self.b_1 = 1.5 * self.delta
        self.b_2 = 2.5 * self.delta
        self.m = 0.85 * self.delta
        self.m_1 = 0.85 * self.delta
        self.d_f_float = 0.036 * a + 12
        self.d_f = bolt(self.d_f_float)
        self.n = number_of_anchor_screws(a)
        self.d_1 = 0.75 * self.d_f
        self.d_2 = round(0.55 * self.d_f)
        self.l = (150, 200)
        self.d_3 = round(0.45 * self.d_f)
        self.d_4 = round(0.35 * self.d_f)
        self.d = round(0.75 * self.d_2)
        self.C_1, self.C_2 = structural_dimensions_of_bosses_and_flanges(self.d_1)

        console.print('ç®±åº§å£åš:', style='yellow')
        print('Î´ â‰¥ ', self.delta, 'mmï¼Œå–Î´ â‰¥ ', self.delta, 'mm')
        console.print('ç®±ç›–å£åšï¼š', style='yellow')
        print('Î´_1 â‰¥ ', self.delta_1, 'mmï¼Œå–Î´_1 =', self.delta_1, 'mm')
        console.print('ç®±ä½“å‡¸ç¼˜åšåº¦ï¼š', style='yellow')
        print('ç®±åº§b = 1.5Î´ =', self.b, 'mmï¼Œç®±ç›–b_1 = 1.5Î´ =', self.b_1, 'mmï¼Œç®±åº•åº§b_2 = 2.5Î´ =', self.b_2, 'mm')
        console.print('åŠ å¼ºè‚‹åšåº¦ï¼š', style='yellow')
        print('ç®±åº§m = 0.85 Î´ = ', self.m, 'mmï¼Œç®±ç›–m_1=0.85Î´_1=', self.m_1, 'mm')
        console.print('åœ°è„šèºé’‰ç›´å¾„ï¼š', style='yellow')
        print('ğ‘‘_ğ‘“=0.036a+12=', self.d_f_float,
              'mmï¼Œå–ğ‘‘_ğ‘“=', self.d_f,
              'ğ‘šğ‘šï¼Œ\nå‹å·ä¸ºï¼šèºæ “GB5782ï¼86 M', self.d_f,
              'Ã—60     é‡‡ç”¨æ ‡å‡†å¼¹ç°§å«åœˆï¼Œå‹å·ï¼šå«åœˆGB93ï¼87 18')
        console.print('åœ°è„šèºé’‰æ•°ç›®ï¼š', style='yellow')
        print('å› aâ‰¤250mmï¼Œå–n=', self.n, 'mm')
        console.print('è½´æ‰¿æ—è”æ¥èºæ “ç›´å¾„ï¼š', style='yellow')
        print('d_1=0.75d_f=', self.d_1,
              'mm\nå‹å·ä¸ºï¼šèºæ “GB5782ï¼86 M', self.d_1,
              'Ã—115   é‡‡ç”¨æ ‡å‡†å¼¹ç°§å«åœˆï¼Œå‹å·ï¼šå«åœˆGB93ï¼87 14')
        console.print('ç®±ç›–ï¼Œç®±åº§è”æ¥èºæ “ç›´å¾„ï¼š', style='yellow')
        print('d_2=0.5d_f=', self.d_2,
              'mm\nå‹å·ä¸ºï¼šèºæ “GB5782ï¼86 M', self.d_2,
              'Ã—40    é‡‡ç”¨æ ‡å‡†å¼¹ç°§å«åœˆï¼Œå‹å·ï¼šå«åœˆGB93ï¼87 10')
        console.print('èºæ “é—´è·:', style='yellow')
        print('Lâ‰¤150~200mm')
        console.print('è§‚å¯Ÿå­”ç›–èºé’‰ç›´å¾„:', style='yellow')
        print('d_4=', self.d_4, 'mm')


class accessories:
    def __init__(self, delta, delta_1, C_1, C_2, a, d):
        self.d = self.b = round(2.15 * delta_1)
        self.R = round(1.1 * self.d)
        self.e = round(0.9 * self.d)

        self.K = C_1 + C_2
        self.H = 0.8 * self.K
        self.h = 0.5 * self.H
        self.r = self.K / 6
        self.b = 2.15 * delta
        console.print('èµ·é‡åŠè€³:', style='yellow')
        print('é‡‡ç”¨åŠè€³ç¯ï¼Œè§å‚è€ƒæ–‡çŒ®P167è¡¨11-3'
              '\nå–å°ºå¯¸d=b=', self.d, 'mmï¼ŒR=', self.R, 'mmï¼Œe=', self.e, 'mm')
        console.print('åŠé’©ï¼š', style='yellow')
        print('å–å°ºå¯¸K=', self.K,
              'mm,H=', self.H,
              'mm,h=', self.h,
              'mm,r=', self.r,
              'mm,b=', self.b,
              'mm\nå…¶ä½™å°ºå¯¸å‚è§è£…é…å›¾ã€‚')

        self.delta_1 = round(1.2 * delta)
        self.delta_2 = round(delta)
        console.print('å‚ç…§å‚è€ƒæ–‡çŒ®[1]P89è¡¨7-9å–æ²¹æ ‡ç®¡å¼æ¸¸æ ‡ã€‚', style='yellow')
        console.print('é½¿è½®é¡¶åœ†è‡³ç®±ä½“å†…å£çš„è·ç¦»ï¼š', style='yellow')
        print('â–³_1â‰¥1.2Î´ï¼Œå–â–³_1=', self.delta_1, 'mm,')
        console.print('é½¿è½®ç«¯é¢è‡³ç®±ä½“å†…å£çš„è·ç¦»ï¼š', style='yellow')
        print('â–³_2â‰¥Î´ï¼Œå–â–³_2=', self.delta_2, 'mm')
        console.print('çª¥è§†å­”åŠè§†å­”ç›–ï¼Œå‚ç…§å‚è€ƒæ–‡çŒ®P:167è¡¨11-4', style='yellow')
        self.hole_cover = hole_cover(a_sum=a)
        print('å–l_1=', self.hole_cover[0],
              'mm,l_2=', self.hole_cover[1],
              'mm,b_1=', self.hole_cover[2],
              'mm,b_2=', self.hole_cover[3],
              'mm,Î´=', self.hole_cover[6],
              'mm,R=', self.hole_cover[7], 'mm ')

        console.print('é€šæ°”å™¨ç”¨é€šæ°”å¡ï¼ŒæŸ¥å‚è€ƒæ–‡çŒ®[1]è¡¨11ï¼5ï¼Œå¾—ä»¥ä¸‹æ•°æ®ï¼š', style='yellow')
        self.vent_plug = vent_plug(d=d)
        print('å–M', d,
              'ï¼ŒD =', self.vent_plug[0],
              'mmï¼ŒD_1=', self.vent_plug[1],
              'mmï¼Œs=', self.vent_plug[2],
              'ï¼ŒL=', self.vent_plug[3],
              'ï¼Œl=', self.vent_plug[4],
              'ï¼Œa=', self.vent_plug[5],
              ' ï¼Œd1=', self.vent_plug[6], 'ã€‚')
        console.print('å¯ç›–èºé’‰ï¼š', style='yellow')
        print('å‹å·ä¸ºï¼šèºæ “GB5782ï¼86 M6Ã—20')


